= Network Customization During OpenShift Bare Metal IPI Installation

== Adding a static route

DHCP can be used to provision additional static routes to the OpenShift nodes.  The example below
uses ISC `dhcpd`, but `dnsmasq` and (presumably) other DHCP servers offer similar functionality.

This example adds a route to the `192.168.135.0/24` subnet via the router at `10.11.173.1`.

First, add the DHCP option definition to `/etc/dhcp/dhcpd.conf`:

```
option classless-static-routes code 121 = array of unsigned integer 8;
```

This option can then be used in both `subnet` and `host` definitions.

To provision the route to all hosts on the subnet:

```
subnet 10.11.173.0 netmask 255.255.255.0 {
	authoritative;
	option domain-name		"pemlab.rdu2.redhat.com";
	option domain-name-servers	10.11.173.1, 8.8.8.8;
	option ntp-servers		10.11.173.1;
	option routers			10.11.173.254;
	option classless-static-routes	24, 192, 168, 135, 10, 11, 173, 1;
	range				10.11.173.101, 10.11.173.200;
}
```

Or to provision the route to only certain hosts:

```
host openshift-master-0 {
        hardware ethernet		52:54:00:de:77:92;
        fixed-address			10.11.173.71;
        option classless-static-routes	24, 192, 168, 135, 10, 11, 173, 1;
}

host openshift-master-1 {
        hardware ethernet		52:54:00:c9:f7:48;
        fixed-address			10.11.173.72;
        option classless-static-routes	24, 192, 168, 135, 10, 11, 173, 1;
}

host openshift-master-2 {
        hardware ethernet		52:54:00:b0:1e:0f;
        fixed-address			10.11.173.73;
        option classless-static-routes	24, 192, 168, 135, 10, 11, 173, 1;
}
```

== The bootstrap VM

In some cases, the bootstrap VM may also require a pre-determined IP address on the baremetal
network.  DHCP cannot be used to assign a pre-determined address, because the bootstrap VM's MAC
address is not known in advance.  Ignition (the configuration mechanism used by Red Hat Enterprise
Linux CoreOS) can be used to customize the bootstrap VM's network configuration.

Red Hat Enterprise Linux CoreOS (RHCOS) uses NetworkManager for network configuration, so
customizing the RHCOS network configuration requires creating the appropriate file(s) in the
`+/etc/sysconfig/network-scripts+` directory.

These files assign a static IP address to the bootstrap VM's baremetal interface.  Because DHCP is
not being used, they also set the DNS server(s), default route, and an additional static route.

TIP: A useful method of initially creating these files is to use the `nmcli` command in a Red Hat
Enterprise Linux (not RHCOS) test VM.  NetworkManager will write create the required files in
`+/etc/sysconfig/network-scripts+` from whence they can be copied to the provisioner node.

*ifcfg-baremetal:*

```
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
IPADDR=10.11.173.69
PREFIX=24
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=baremetal
UUID=9491dcd8-c782-40a4-ac5c-97557c51c64a
DEVICE=ens3
ONBOOT=yes
GATEWAY=10.11.173.254
DNS1=127.0.0.1
DNS2=10.11.173.1
```

IMPORTANT: `127.0.0.1` must be the first DNS server listed.  The bootstrap VM will run a CoreDNS
container, which will provide name resolution for internal cluster names.  This must be the first
DNS server listed in `/etc/resolv.conf`.

*route-baremetal:*

```
ADDRESS0=192.168.135.0
NETMASK0=255.255.255.0
GATEWAY0=10.11.173.1
```

During a normal bare metal IPI installation, the OpenShift installer creates and uses its ignition
files as part of the `create cluster` step.  Modifying the bootstrap VM's ignition file requires
that the ignition files be explicitly generated as a separate step.

Assuming that an appropriate `+install-config.yaml+` file has been copied into the (otherwise empty)
`+~/clusterconfigs+` directory, the following commands will generate the ignition files.

```
[kni@installer ~]$ *openshift-baremetal-install --dir clusterconfigs create manifests*
INFO Consuming Install Config from target directory 
WARNING Discarding the Openshift Manifests that was provided in the target directory because its dependencies are dirty and it needs to be regenerated

[kni@installer ~]$ openshift-baremetal-install --dir clusterconfigs create ignition-configs
INFO Consuming Master Machines from target directory 
INFO Consuming Openshift Manifests from target directory 
INFO Consuming Common Manifests from target directory 
INFO Consuming OpenShift Install (Manifests) from target directory 
INFO Consuming Worker Machines from target directory
```

The bootstrap VM's ignition file will be found at `+clusterconfigs/bootstrap.ign+`.  It is an
unformatted JSON file.  The `jq` utility can be used to create a formatted version for easier
editing.

```
[kni@installer ~]$ jq . clusterconfigs/bootstrap.ign > /tmp/bootstrap.json
```

Examine `/tmp/bootstrap.json` and note `storage` section.

```
⋮
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/containers/registries.conf",
        "user": {
          "name": "root"
        },
        "contents": {
          "source": "data:text/plain;charset=utf-8;base64,",
          "verification": {}
        },
        "mode": 384
      },
      {
        "filesystem": "root",
        "path": "/etc/ignition-machine-config-encapsulated.json",
        "user": {
          "name": "root"
        },
        "contents": {
          "source": "data:text/plain;charset=utf-8;base64,ewogICJtZXRhZGF0YSI6IHsKICAgICJuYW1lIjogImJvb3RzdHJhcC1maXBzIgogIH0sCiAgInNwZWMiOiB7CiAgICAiY29uZmlnIjogewogICAgICAiaWduaXRpb24iOiB7CiAgICAgICAgInZlcnNpb24iOiAiMi4yLjAiCiAgICAgIH0KICAgIH0sCiAgICAia2VybmVsQXJndW1lbnRzIjogW10sCiAgICAiZmlwcyI6IGZhbHNlCiAgfQp9Cg==",
          "verification": {}
        },
        "mode": 384
      },
⋮
```

The format is straightforward.  The stanzas shown above create 2 different files on the root
filesystem, `+/etc/containers/registries.conf+` and
`+/etc/ignition-machine-config-encapsulated.json+`.  Both are owned by `root`, and both have
`0600` permissions, i.e. readable and writable only by their owner.  (*384* decimal is equal to
*600* octal.)

`+registries.conf+` is an empty file; there are no actual contents in the `source` item.
The contents of `+ignition-machine-config-encapsulated.json+` are determined by the base64
encoded string which follows the "preamble" of its `source`.

```
[kni@installer ~]$ echo -n ewogICJtZXRhZGF0YSI6IHsKICAgICJuYW1lIjogImJvb3RzdHJhcC1maXBzIgogIH0sCiAgInNwZWMiOiB7CiAgICAiY29uZmlnIjogewogICAgICAiaWduaXRpb24iOiB7CiAgICAgICAgInZlcnNpb24iOiAiMi4yLjAiCiAgICAgIH0KICAgIH0sCiAgICAia2VybmVsQXJndW1lbnRzIjogW10sCiAgICAiZmlwcyI6IGZhbHNlCiAgfQp9Cg== | base64 -d
{
  "metadata": {
    "name": "bootstrap-fips"
  },
  "spec": {
    "config": {
      "ignition": {
        "version": "2.2.0"
      }
    },
    "kernelArguments": [],
    "fips": false
  }
}
```

NOTE: `verification` can be used to check the hash values of files whose contents are pulled from
external (HTTP) sources.

Using ignition to add the network configuration files (`+ifcfg-baremetal+` and `+route-baremetal+`)
requires the base64 encoded contents of those files.  Assuming that the files have been copied to
`+~/network+`:

```
[kni@installer ~]$ base64 -w0 network/ifcfg-baremetal && echo
VFlQRT1FdGhlcm5ldApQUk9YWV9NRVRIT0Q9bm9uZQpCUk9XU0VSX09OTFk9bm8KQk9PVFBST1RPPW5vbmUKSVBBRERSPTEwLjExLjE3My42OQpQUkVGSVg9MjQKREVGUk9VVEU9eWVzCklQVjRfRkFJTFVSRV9GQVRBTD1ubwpJUFY2SU5JVD15ZXMKSVBWNl9BVVRPQ09ORj15ZXMKSVBWNl9ERUZST1VURT15ZXMKSVBWNl9GQUlMVVJFX0ZBVEFMPW5vCklQVjZfQUREUl9HRU5fTU9ERT1zdGFibGUtcHJpdmFjeQpOQU1FPWJhcmVtZXRhbApVVUlEPTk0OTFkY2Q4LWM3ODItNDBhNC1hYzVjLTk3NTU3YzUxYzY0YQpERVZJQ0U9ZW5zMwpPTkJPT1Q9eWVzCkdBVEVXQVk9MTAuMTEuMTczLjI1NApETlMxPTEyNy4wLjAuMQpETlMyPTEwLjExLjE3My4xCg==

[kni@installer ~]$ base64 -w0 network/route-baremetal && echo
QUREUkVTUzA9MTkyLjE2OC4xMzUuMApORVRNQVNLMD0yNTUuMjU1LjI1NS4wCkdBVEVXQVkwPTEwLjExLjE3My4xCg==
```

NOTE: `-w0` prevents the `base64` command from wrapping its output.  Adding an `echo` at the end
makes the output easier to distinguish by placing the prompt at the beginning of the following line.

Edit `/tmp/bootstrap.json` and add stanzas for the network configuration files at the
beginning of the `storage` section.  The `mode` of each file should be `0644`, which is expressed
as *420* in decimal.

```
⋮
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/sysconfig/network-scripts/ifcfg-baremetal",
        "user": {
          "name": "root"
        },
        "contents": {
          "source": "data:text/plain;charset=utf-8;base64,VFlQRT1FdGhlcm5ldApQUk9YWV9NRVRIT0Q9bm9uZQpCUk9XU0VSX09OTFk9bm8KQk9PVFBST1RPPW5vbmUKSVBBRERSPTEwLjExLjE3My42OQpQUkVGSVg9MjQKREVGUk9VVEU9eWVzCklQVjRfRkFJTFVSRV9GQVRBTD1ubwpJUFY2SU5JVD15ZXMKSVBWNl9BVVRPQ09ORj15ZXMKSVBWNl9ERUZST1VURT15ZXMKSVBWNl9GQUlMVVJFX0ZBVEFMPW5vCklQVjZfQUREUl9HRU5fTU9ERT1zdGFibGUtcHJpdmFjeQpOQU1FPWJhcmVtZXRhbApVVUlEPTk0OTFkY2Q4LWM3ODItNDBhNC1hYzVjLTk3NTU3YzUxYzY0YQpERVZJQ0U9ZW5zMwpPTkJPT1Q9eWVzCkdBVEVXQVk9MTAuMTEuMTczLjI1NApETlMxPTEyNy4wLjAuMQpETlMyPTEwLjExLjE3My4xCg==",
          "verification": {}
        },
        "mode": 420
      },
      {
        "filesystem": "root",
        "path": "/etc/sysconfig/network-scripts/route-baremetal",
        "user": {
          "name": "root"
        },
        "contents": {
          "source": "data:text/plain;charset=utf-8;base64,QUREUkVTUzA9MTkyLjE2OC4xMzUuMApORVRNQVNLMD0yNTUuMjU1LjI1NS4wCkdBVEVXQVkwPTEwLjExLjE3My4xCg==",
          "verification": {}
        },
        "mode": 420
      },
      {
        "filesystem": "root",
        "path": "/etc/containers/registries.conf",
⋮
```

`jq` can be used again to write the edited JSON out in "compact" form as the new ignition file.

```
[kni@installer ~]$ jq -c . /tmp/bootstrap.json > clusterconfigs/bootstrap.ign
```

Now the OpenShift installation can be completed.

```
[kni@installer ~]$ openshift-baremetal-install --dir clusterconfigs --log-level debug create cluster
⋮
```
